### ISSUE TITLE
consider HfsPlus.efi also?

### ISSUE THREAD

**Issue by cattyhouse** [rusty-bits/OC-tool#1]
I like HfsPlus.efi over VboxHFS.efi, it is faster when used to boot Recovery. but this tool does not work if HfsPlus.efi is used.

ERROR: HfsPlus.efi - repo was not found in Docs/repo.plist or extras

**Comment by rusty-bits** [comment]
Do you have HfsPlus.efi in the extras directory? If you do and the tool does not find it there is an issue.  

Files that can't be built on the fly, such as HfsPlus.efi, need to be placed in the extras directory.

**Comment by cattyhouse** [comment]
Oh, i see, thanks.
