### ISSUE TITLE
ERROR: vault build failed

### ISSUE THREAD

**Issue by lignicolos** [rusty-bits/OC-tool#12]
Hello, when I run ./OC-tool -d it builds an EFI and then I get the error below"

`Building vault files for /Users/josh/Hackintosh/OC-tool/OUTPUT/EFI ... ERROR: vault build failed, see /Users/josh/Hackintosh/OC-tool/tool.log for details`

When I check the tool.log file I see the message below:

`dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /Users/josh/Hackintosh/OC-tool/resources/prebuiltDaily/UDK/OcSupportPkg/Utilities/RsaTool/RsaTool
  Reason: image not found
./OC-tool: line 597:  9003 Abort trap: 6           "$RES_DIR"/UDK/OcSupportPkg/Utilities/RsaTool/RsaTool -sign vault.plist vault.sig vault.pub`

I checked my /usr/local/opt/openssl/lib/ folder and I've got libcrypto.1.1.dylib, not the 1.0.0 referenced. I am using homebrew to install openssl. Any ideas on how I can fix this?

**Comment by rusty-bits** [comment]
hmm, I'm wondering if putting a symlink to libcrypto.1.1.dylib would work

can you try something like this?

`cd /usr/local/opt/openssl/lib`
`ln -s libcrypto.1.1.dylib libcrypto.1.0.0.dylib`

either that or put the actual 1.0.0.dylib in the lib folder as well, but I would try the symlink first and see if it works

**Comment by lignicolos** [comment]
tried the symlink and it didn't work, but installing openssl 1.0.2t did work and allowed the EFI to be built successfully. Thanks!
