### ISSUE TITLE
OpenSSL

### ISSUE THREAD

**Issue by amiles5** [rusty-bits/OC-tool#17]
[tool.log](https://github.com/rusty-bits/OC-tool/files/4198804/tool.log)
Hi Rusty,

Keeping up with OC changes today and noticed I had t turn off vault since it wouldn't build on my machine.

> cc -Wall -Wextra -pedantic -O3 -I/usr/local/opt/openssl/include -I/opt/local/include  -L/usr/local/opt/openssl/lib -L/opt/local/lib -lcrypto  RsaTool.c   -o RsaTool
> In file included from RsaTool.c:14:
> ./openssl_compat.h:20:10: fatal error: 'openssl/opensslv.h' file not found
> #include <openssl/opensslv.h>
>          ^~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> make: *** [RsaTool] Error 1

Everything else builds fine. I'm on Catalina 10.15.3 with Xcode Version 11.3.1 (11C504)

Which openssl do I need?

(Great resource !!)

**Comment by amiles5** [comment]
Running X option changes the error to 

> dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
>   Referenced from: /Users/milesj/OC-tool/resources/prebuiltDaily/UDK/OcSupportPkg/Utilities/RsaTool/RsaTool
>   Reason: image not found
> ./OC-tool: line 609: 18101 Abort trap: 6           "$RES_DIR"/UDK/OcSupportPkg/Utilities/RsaTool/RsaTool -sign vault.plist vault.sig vault.pub

which is the same error as issue #12.

So looks like I need openssl 1.0.2t

**Comment by amiles5** [comment]
openssl@1.1 allowed vault to build.

**Comment by rusty-bits** [comment]
It looks like the same issue lignicols had four days ago.  They had openssl installed with homebrew which gave them libcrypto.1.1.dylib which wouldn't let their vault build either.

**Comment by rusty-bits** [comment]
Good to know that openssl@1.1 worked, not quite sure how I could put a check in for that, I'm just having OC-tool run acidanthera's tools to build the vault and RsaTool.
I will at least change the error message to include the versions of openssl that work.

**Comment by amiles5** [comment]
All good now - do you need to list this issue in your tool prereq's ?

Thanks

**Comment by rusty-bits** [comment]
Yes, probably a good idea to list the issue. I'm just trying to find the best way to do a check.
Thanks for the report and info.
