### ISSUE TITLE
Request: naming for modified custom plist

### ISSUE THREAD

**Issue by E-werd** [rusty-bits/OC-tool#19]
Currently, if you make changes in the TUI, your plist is saved indiscriminately as "modified.config.plist".  This would make sense if you're modifying config.plist, but not in the case where you supply a custom plist, e.g. "usb.config.plist".  This is my case as my USB version has different values for ShowPicker and Timeout.

My suggestion: where $1 is the specified (or default) filename, rename the modified file to "modified.$".  This means that a specified file "usb.config.plist" would become "modified.usb.config.plist".

**Comment by rusty-bits** [comment]
I like that, I'll get that change in sometime tonight.

Right now if you use INPUT/modified.config.plist as the input file any changes will be written back to it.  I think I'm going to keep it like that so I don't wind up with modified.modified.config.plist and modified.modified.modified.config.plist etc

Anything without modified. at the start of the filename will have edits saved with a modified.originalName.plist
