### ISSUE TITLE
Suggestion: Kexts in Extras Takes Higher Priority

### ISSUE THREAD

**Issue by hftsai256** [rusty-bits/OC-tool#23]
**Is your feature request related to a problem? Please describe.**
DW1820A is a problematic card with lots of different flavors, and people may have to customize their BrcmPatchRAM3.kext to their need to make the correct firmware being uploaded (refer to [this issue](https://github.com/acidanthera/bugtracker/issues/715)).

**Describe the solution you'd like**
It would be great if it accepts user-provided kexts in extras folder and create vault signatures. In other words, if a specific kext is shown in extras folder, use the user-provided one instead of the pre-built/built-from-source one. It could be implemented as an dedicated flag to trigger it, or just implemented as the default behavior and leave a warning message to people who may be unaware of this new feature.

**Additional context**
I'm ordering two more DW1820A with different flavors and is planning to test them out upon arrival.

**Comment by rusty-bits** [comment]
just changed the tool in commit d8cacd8 to check extras first for all resources, not just the ACPI files  

I can't remember why I had it that way, but lets see if this breaks anything else 🤔
