### ISSUE TITLE
[Question] Add missing lines

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#29]
How do I add missing lines using OC-Tools?

<a href="https://imgur.com/AsuJueR"><img src="https://i.imgur.com/AsuJueR.jpg" title="source: imgur.com" /></a>

<a href="https://imgur.com/bQQ35bh"><img src="https://i.imgur.com/bQQ35bh.jpg" title="source: imgur.com" /></a>

<a href="https://imgur.com/iM7xFNn"><img src="https://i.imgur.com/iM7xFNn.jpg" title="source: imgur.com" /></a> 

Thanks

**Comment by rusty-bits** [comment]
Hopefully you figured it out already, but in case you haven't here's what you need to do ...  
On your first run when OC-tool showed the missing Misc>Security>BootProtect you ran the tool using the command
`./OC-tool -s`  
![A2A5D86D-1B63-421B-A280-A06A93B58F59](https://user-images.githubusercontent.com/46965981/80218181-d8039900-860e-11ea-956d-beab94d33bb2.jpeg)
which will build 0.5.8 from source  
it gave the message to use `./OC-tool -ts` to add the missing field, but you didn't include the `s` to build from latest source  
![0AA7D2E0-FCF3-4505-86BA-E4F41EF38E76](https://user-images.githubusercontent.com/46965981/80218639-7132af80-860f-11ea-8de7-9c15444f9039.jpeg)
which means OC-tool will do a prebuiltRelease 0.5.7  

you need to run `./OC-tool -ts` to edit with the TUI and then build from source

**Comment by Blurayx** [comment]
Thanks 🙂
