### ISSUE TITLE
Tool fails at copying AppleGenericInput.efi to OC/Drivers

### ISSUE THREAD

**Issue by lignicolos** [rusty-bits/OC-tool#3]
So I ran the tool just a few minutes ago using ./OC-tool build release and the process dies at "Copying AppleGenericInput.efi to OC/Drivers ... %"

the tool.log file says 
"- Done -
Build end time: 13:58:15, Oct.06 2019
Build total time: 00:00:20

cp: /Users/joshua/Hackintosh/OC-tool/resources/UDK/Build/AppleSupportPkg/RELEASE_XCODE5/X64/AppleGenericInput.efi: No such file or directory"

![Screen Shot 2019-10-06 at 2 03 26 PM](https://user-images.githubusercontent.com/27593909/66273445-15a2ff00-e842-11e9-8fca-b03849bb46d1.png)

**Comment by rusty-bits** [comment]
It looks like I missed a change the acidanthera team made.  
AppleGenericInput.efi has been removed from the AppleSupportPkg and migrated into OcSupportPkg  
It is no longer placed in UEFI>Drivers in config.plist  
It now appears that there is a UEFI>Input section in config.plist for Input settings  
I just removed AppleGenericInput.efi from OC-tool's repo.list, and was able to complete a build, let me know if it works for you.

**Comment by lignicolos** [comment]
Success! I updated my config.plist to match the new input stuff and OC-tool built a new EFI folder and it booted properly. Thanks for the fix!

**Comment by rusty-bits** [comment]
good to hear, thanks for reporting the issue
