### ISSUE TITLE
Parsing of latest config.plist is off

### ISSUE THREAD

**Issue by locussss** [rusty-bits/OC-tool#30]
Hi,

With the latest update on OC-tool the parsing of config.plist is off.
I have attached two screenshots, one of the contents of extra and one of the terminal with the latest ./OC-tool -s and the latest source.

<img width="882" alt="OC-tool" src="https://user-images.githubusercontent.com/58507126/80301548-1c28a200-87a5-11ea-9a52-bd91ed7671ad.png">

<img width="1032" alt="terminal" src="https://user-images.githubusercontent.com/58507126/80301572-2a76be00-87a5-11ea-8d4e-2f40cf6f0d0a.png">

There are in Sample.plist a couple of drivers added with an # in front so not active.
I have included it in my config.plist in the same way.

OC-tool stops with the error that it can't find (for instance) #UsbMouseDxe.efi

**Comment by rusty-bits** [comment]
added  
UsbMouseDxe.efi  
Ps2KeyboardDxe.efi  
Ps2MouseDxe.efi  
to the git_repo.json file so OC-tool knows where to find the resources and won't error out  

Thanks for pointing it out
