### ISSUE TITLE
[Question] Errors

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#32]
Hi Rusty,

Getting build failed errors when updating. Can you please look at my log file
[tool.log](https://github.com/rusty-bits/OC-tool/files/4567231/tool.log)
<a href="https://imgur.com/6FjHoK6"><img src="https://i.imgur.com/6FjHoK6.png" title="source: imgur.com" /></a>

Thanks

**Comment by Blurayx** [comment]
Fixed. There was an issue with the OpenCorePkg package on GitHub. It's now been updated
🙂

**Comment by rusty-bits** [comment]
Glad they fixed it on their end.
