### ISSUE TITLE
[Question ] Bump Version to 0.59 

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#33]
Updating to 0.5.9 worked fine but OC-tool is still showing 0.58

<a href="https://imgur.com/3Fhht4x"><img src="https://i.imgur.com/3Fhht4x.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/fbou5ID"><img src="https://i.imgur.com/fbou5ID.png" title="source: imgur.com" /></a>

After OC-tool update from version 0.58 to 0.59
<a href="https://imgur.com/CxXFOWz"><img src="https://i.imgur.com/CxXFOWz.jpg" title="source: imgur.com" /></a>

**Comment by rusty-bits** [comment]
Remember, I'm lazy 😉   
Sometimes I don't get around to updating the release version for days.  I have to update a "few" files to change the release info correctly.  
![71133C1D-2A4B-424D-8A1B-90DC98D4F5DF](https://user-images.githubusercontent.com/46965981/80973990-1d358100-8dee-11ea-8ab6-8bce72c344dd.jpeg)

I had time today, though, and commit 4058fc9 is up to 0.5.8

**Comment by Blurayx** [comment]
lol no worries.

Thanks
