### ISSUE TITLE
[Bug] updating

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#34]
when I upgrade to a new version of 0.59. the config.plist looks the same as my original but the graphical mode does not work. I get the default boot screen instead.
All my files are in the correct folders
e.g
<a href="https://imgur.com/k9n3cto"><img src="https://i.imgur.com/k9n3cto.jpg" title="source: imgur.com" /></a>
Input folder
<a href="https://imgur.com/ZYDiQK5"><img src="https://i.imgur.com/ZYDiQK5.png" title="source: imgur.com" /></a>
output folder
<a href="https://imgur.com/BrixNop"><img src="https://i.imgur.com/BrixNop.png" title="source: imgur.com" /></a>

Output->EFI->OC->Resources->image
<a href="https://imgur.com/m8UAjEy"><img src="https://i.imgur.com/m8UAjEy.png" title="source: imgur.com" /></a>

Graphical mode
<a href="https://imgur.com/nE7ETB0"><img src="https://i.imgur.com/nE7ETB0.jpg" title="source: imgur.com" /></a>

**Comment by rusty-bits** [comment]
Did you change your settings in your config.plist to use something other than the default picker?
Did you include the files and drivers needed for a different picker?

Why would you call this a bug?  What bug?

**Comment by Blurayx** [comment]
when I upgraded from 57 to 58, including the daily 58 updates I still retained my Graphical mode with picker set to external I didn't have any issues.

1) picker set to External
<a href="https://imgur.com/9o9vxIp"><img src="https://i.imgur.com/9o9vxIp.png" title="source: imgur.com" /></a>
2 Yes. 
3)? ¯\_(ツ)_/
I still had the same issue when I compiling my EFI folder with OC Builder then put the necessary drivers into OC-tool

**Comment by rusty-bits** [comment]
I'm not sure what this has to do with OC-tool, especially if you have the same issue with OC Builder.  
Maybe you found a bug in OpenCore? I don't know, you could check with the OpenCore developers, but that has nothing to do with OC-tool.  

Also, did you check all your configurations? Particularly PickerAttributes? Because, your setting doesn't look right to me.

**Comment by Blurayx** [comment]
my PickerAttributes setting has always been the same.
I'll update manually from now on.

Thanks

**Comment by rusty-bits** [comment]
I'm glad you found something that works for you.  
Keep in mind that the default for PickerAttributes changed to 1 in OC 0.5.8  
Also make sure to keep your OcBinaryData up to date, such as the new Fonts they added 3 days ago, so your graphical mode isn't affected.

**Comment by Blurayx** [comment]
I decided to give OC-tool another go with your recommended settings. it worked! 😀 

Thank you
