### ISSUE TITLE
Copying HFSPlus.efi fails on a case-sensitive file system

### ISSUE THREAD

**Issue by Sap1k** [rusty-bits/OC-tool#37]
Here is the tool log. From what I can tell, the script checks that HfsPlus.efi exists, but tries to copy HFSPlus.efi. This theory is confirmed by placing both files in the extras directory. If that is done, the script finishes successfully.
Hoping you can fix this :)
* [tool.log](https://github.com/rusty-bits/OC-tool/files/4817960/tool.log)

**Comment by rusty-bits** [comment]
Since so many people were using HFSPlus.efi instead of HfsPlus.efi I had code in there that would let OC-tool use either one.  
I thought I had cleaned it all up back when acidanthera included HfsPlus.efi in the OpenCorePkg, but obviously not.
