### ISSUE TITLE
get-reps.sh cannot fetch mtoc

### ISSUE THREAD

**Issue by HQuest** [rusty-bits/OC-tool#38]
acidanthera team moved the mtoc compressed binary file to a new name and added a symlink instead; this is causing the get-reps.sh script to fail to load it as GitHub doesn't serve the destination file via a link as a regular web server would.

**Comment by rusty-bits** [comment]
thanks for the info, I'll try to take care of that this weekend

**Comment by rusty-bits** [comment]
updated get-reps.sh to reflect changes in https://github.com/acidanthera/ocbuild/blob/master/efibuild.sh   

tested on Catalina and Big Sur with Xcode beta 12
