### ISSUE TITLE
Failing to retrieve correct versions of VirtualSMC & WhateverGreen

### ISSUE THREAD

**Issue by amiles5** [rusty-bits/OC-tool#4]
Hi Rusty,

First of all thanks for this great tool!!

I have two hacks and on one of them your tool fails to pickup the latest release of VirtualSMC (1.0.7 rather than 1.0.8) and WhateverGreen (1.3.2 rather than 1.3.3) 

Not sure where its going wrong?
[tool.log](https://github.com/rusty-bits/OC-tool/files/3706706/tool.log)

**Comment by rusty-bits** [comment]
I just checked on my machine, same problem.  
If I make a test folder and clone and build VirtualSMC there I get 1.0.8  
If I try inside OC-tool/resources/Kext-builds I get 1.0.7  
I'm searching to see what is different.

**Comment by rusty-bits** [comment]
It is looking like an Xcode 11 issue, possibly old and new DerivedData in the Library files  
I may have to upgrade my Xcode, but I'm not sure how to do that from the command line, not at my computer at the moment, just have a shell connection to it.  

As a current workaround here is what I did on my computer.
`rm -rf ~/Library/Developer/Xcode/DerivedData`  
`./OC-tool -X build release`

This cleaned out the cache of old data on Xcode, then wiped the OC-tool resources directory and built a RELEASE EFI  

All versions look up to date for me, now have ...  
VirtualSMC 1.0.8  
WhateverGreen 1.3.3

**Comment by rusty-bits** [comment]
![1259CF4D-51D7-4121-B9D0-0025C9B35642](https://user-images.githubusercontent.com/46965981/66500025-dfa68a80-ea8e-11e9-9432-f45a1a0d3e8e.jpeg)

--snip--  

![F038EA47-C7AF-42C4-8928-C5D85FD82BFC](https://user-images.githubusercontent.com/46965981/66500026-e03f2100-ea8e-11e9-9c8d-65cd9d03bf48.jpeg)

**Comment by amiles5** [comment]
yep - fixed it fo me too :-)

<img width="956" alt="Screenshot 2019-10-09 at 17 40 04" src="https://user-images.githubusercontent.com/12343787/66501770-ee576680-eabb-11e9-97c8-a73935216a05.png">

thanks !!

**Comment by rusty-bits** [comment]
pushed change...   
-X option now also removes Xcode DerivedData for resources being built  
should prevent Xcode 11 from using wrong build info  
thanks for pointing it out.
