### ISSUE TITLE
Not working after a new install

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#40]
When OC-tool automatically updated to the latest release everything worked great.
I deleted/reinstalled OC-too. Now it will not generate an EFI in the output folder. All my files are in the correct folders.
macOS Catalina 
<a href="https://imgur.com/dKGsSxx"><img src="https://i.imgur.com/dKGsSxx.png" title="source: imgur.com" /></a>

macOS Big Sur Beta3 stops @ "Building new or updated resources"
<a href="https://imgur.com/ZDlV52K"><img src="https://i.imgur.com/ZDlV52K.png" title="source: imgur.com" /></a>

Thanks

**Comment by rusty-bits** [comment]
Obviously I broke something, let me see if I can reproduce that trouble on my end.  If I can't I might need to see your tool.log or config.plist.

**Comment by Blurayx** [comment]
I hope this hepls 
[config.plist.zip](https://github.com/rusty-bits/OC-tool/files/4974434/config.plist.zip)
[tool.log.zip](https://github.com/rusty-bits/OC-tool/files/4974435/tool.log.zip)

**Comment by rusty-bits** [comment]
I found a problem, OC-tool doesn't know what to do with the empty Tools section.  Might take me a bit to figure out a good way to have it ignore an empty section, or figure out what I broke if it was in there already.  

Until then you can add a tool back into the Tools section, should work fine even if you have enabled set to false.

**Comment by Blurayx** [comment]
Thank You 😀

**Comment by rusty-bits** [comment]
Should be all set, can build with a blank Tool section over on my end.

**Comment by Blurayx** [comment]
Working perfectly. This software is so valuable to me couldn't live without it!!  
![default_thumbsup_anim](https://user-images.githubusercontent.com/2873112/88462531-ed08f600-cea3-11ea-8727-c641030c6ecc.gif)


Thank you for fixing it so quickly. I hope it wasn't too difficult to fix.
