### ISSUE TITLE
Suggestion: Copy "extras/Resources" if OpenCanopy is detected; warn if folder is missing

### ISSUE THREAD

**Issue by HQuest** [rusty-bits/OC-tool#41]
Title says it all ;)

**Comment by rusty-bits** [comment]
That makes sense.  It should only copy those resources if OpenCanopy is enabled except for maybe the startup chime, pretty sure you can have that without OpenCanopy  
I'll need to check for chime being enabled, but probably not voice over, I think that would only make sense with OpenCanopy

**Comment by HQuest** [comment]
Most folks will leave their "Resources" folder ready with all they need, so it is another "set it and forget it" kind of folder. Not sure how often OpenCanopy changes that requires the resources to be updated, but I suspect this will be a very low incidence. To keep it simple, I would think a simple copy - as you do with any non-acidanthera kext file - should suffice. And yes, "if OpenCanopy.efi then copy extra/Resources; if extra/Resources not found, warn user". This should also help with the signing and vault (hint hint on positioning of the copy process :D)

**Comment by rusty-bits** [comment]
This should take care of it.  I think the last change to Resources was the addition of the Label folder, the user should at least get some kind of warning now if they have OpenCanopy enabled but are missing resources.  
Now it will only copy them if OpenCanopy is enabled, or it will only copy Audio if they only have PlayChime enabled.

**Comment by HQuest** [comment]
What's the rationale of the Resources being looked for on "INPUT" folder instead of the "extras"?

**Comment by rusty-bits** [comment]
I know I had a reason for them being in INPUT instead of extras, but I don't remember exactly what it was.  I made that change back in March.  Something to do with wanting to keep extras as a folder that overrides all versions, even if something newer exists.  
Anyways, thanks to your suggestion, it now only copies them if OpenCanopy is enabled instead of always copying them no matter what.  Thanks.
