### ISSUE TITLE
-arch x86_64 required for builds using Xcode 12

### ISSUE THREAD

**Issue by HQuest** [rusty-bits/OC-tool#43]
Please see discussion @ https://github.com/acidanthera/bugtracker/issues/1059#issuecomment-667548290

**Comment by rusty-bits** [comment]
Thanks for the info, I'll check it out.  Just finished installing a clean Bug Sur beta 3

**Comment by rusty-bits** [comment]
installed Xcode 12 beta 3   
cloned OC-tool   
installed nasm   
installed mtoc   
 
tried building Docs/Sample.plist with no changes   
build failed on Lilu   
added -arch x86_64 to xcodebuild commands in OC-tool, builds fine. Seems faster than Catalina as well.   

will push a new commit later when I reboot into Catalina and test a few things there, thank you

**Comment by rusty-bits** [comment]
looking good on this end, thanks again
