### ISSUE TITLE
Version 2.0.8 of AirportBrcmFixup.kext breaks OCtool

### ISSUE THREAD

**Issue by amiles5** [rusty-bits/OC-tool#45]
Hi Rusty,

AirportBrcmFixup.kext has changed configuration

"Remove injectors for AirPortBrcm4360 and AirPortBrcmNIC from main Info.plist and move them into separate plugins"

Getting this error now 

ERROR:	AirPortBrcm4360_Injector.kext - resource was not found in /Users/milesj/OC-tool/.tool-files/git_repo.json
	AirPortBrcm4360_Injector.kext file not found in extras directory
	Check the spelling of the resource, case matters as well.
	Also check the Configuration.pdf and the Sample.plist to be
	sure the resource hasn't been removed or renamed.
	If you are sure you want this resource then you can
	either place AirPortBrcm4360_Injector.kext in extras directory to build EFI with AirPortBrcm4360_Injector.kext
	or run with -i option to build EFI without AirPortBrcm4360_Injector.kext
	for example, try './OC-tool -is'

tried fixing with './OC-tool -is' but that trashes the config.plist. Premature EOF.

milesj@iMac OC-tool % cat last_run_issues.txt
plutil could not convert plist

Happy Days !!

**Comment by rusty-bits** [comment]
Thanks,  
If I'm reading the notes of AirportBrcmFixup correctly it look like AirPortBrcm4360 and AirPortBrcmNIC are now PlugIns of AirportBrcmFixup.kext   

I'll fix OC-tool as soon as I can

**Comment by rusty-bits** [comment]
added  

AirPortBrcm4360_Injector.kext  
AirPortBrcmNIC_Injector.kext  

as PlugIns of AirportBrcmFixup.kext, fixed building on this end
