### ISSUE TITLE
Request/Bug: Adding VoodooI2C.kext to extra/ causes VoodooI2C artifacts to be stored underneath itself

### ISSUE THREAD

**Issue by HQuest** [rusty-bits/OC-tool#46]
Quite confusing title, but here it goes: Laptops using I2C type of touch devices are expected to use VoodooI2C files (assuming the pre-compiled, official release ones to make matters easy). These files in Clover are just added with no particular order as they are loaded in demand whenever needed. In OC, there is a particular order to inject the core I2C kernel extension, as follows:

```
VoodooI2C.kext/Content/Plugins/VoodooI2CServices.kext
VoodooI2C.kext/Content/Plugins/VoodooGPIO.kext
VoodooI2C.kext

```
, followed by any of the satellite kexts for your hardware.

By OC-tool's default behavior, in order for a file to be added into the config.plist, it has to exist at extra/ folder and not underneath another folder inside extra/. Which in this case, we have to extract it from inside the kernel extension.

Now, by adding the VoodooI2C kernel extension in this particular order (otherwise the device does not work - see Lilu and its companion extensions), since a folder called VoodooI2C.kext is first created when VoodooI2CServices.kext is copied on OUTPUT/EFI (it obeys the BundlePath from the Kext > Add > item X), the VoodooI2c.kext kernel extension itself gets copied underneath it. Ends up as follows:

```
VoodooI2C.kext/Content/Plugins/VoodooI2CServices.kext
VoodooI2C.kext/Content/Plugins/VoodooGPIO.kext
VoodooI2C.kext/VoodooI2C.kext
VoodooI2C.kext/VoodooI2C.kext/Content/Plugins/VoodooI2CServices.kext
VoodooI2C.kext/VoodooI2C.kext/Content/Plugins/VoodooGPIO.kext

```
While a quick workaround is just remove the entire VoodooI2C.kext and copy it back from extras/, perhaps would be if the copy process of kernel extensions created as "plugins" (*looks at VirtualSMC plugins*) to verify if their parent extension is also added into the list, and if so, don't copy the child plugins if the parent is also in the list of artifacts to be copied. This way we don't need to dissect an extension, which makes updates easier to be managed and maintained.

The drawback of the above is if you are building a parent from sources and want to use a custom built plugin. Which should be very rare, as they should be aligned for feature parity/proper functionality.

Hope this makes sense.

**Comment by rusty-bits** [comment]
> The drawback of the above is if you are building a parent from sources and want to use a custom built plugin.   

Once I get around to adding VoodooI2C to the known sources that shouldn't be a problem.   

As to the current issue with VoodooI2C from the extras folder, I didn't know that OC needed them injected in that order.  You're correct that adding a plugin before the parent causes the problem you're seeing.  

I'm going to add a deferred copy to OC-tool for anytime it sees a resource in the config.plist that goes into a parent resource.  This way it will only copy standalone or parent resources first, then it will copy any children once the parents(if any) are in place.

**Comment by rusty-bits** [comment]
ran a few tests overnight, looks okay here   

added support for VoodooI2C prebuilt releases as well, will have to work on compiling them from source in the future, not sure how to automate its build process yet, it's a bit different from the acidanthera resources
