### ISSUE TITLE
Add support to ocvalidator tool

### ISSUE THREAD

**Issue by HQuest** [rusty-bits/OC-tool#47]
While a simple diff from key/value pairs is enough to identify what's extra and what's missing against a sample configuration, the Acidanthera team offers a tool called ocvalidator (previously ConfigValidity) within their suite of programs. Happy if this tool could be added into the list of compiled artifacts OC-tool generates during source work. Since it too is distributed with their releases, it could be ran at an early or late point of the EFI build process as a sanity check, either automatically or as a command flag.

**Comment by rusty-bits** [comment]
I might be missing something but I don't see the benefit of OC-tool using ocvalidator to check the config.plist   

OC-tool already compares the users config.plist against the Sample.plist for any missing or extra fields  
![2DFD6882-9F20-40B0-B14A-9F665E89AA7A](https://user-images.githubusercontent.com/46965981/90769769-c7161c00-e2be-11ea-847d-408e4129b53f.jpeg)  

and provides the info that ocvalidator provides  
![11202723-65F4-4657-8AD3-58E40590EDD2](https://user-images.githubusercontent.com/46965981/90769877-f3ca3380-e2be-11ea-9f4e-5690bd849650.jpeg)  

OC-tool also shows missing fields, like these  
![316E4FEF-CC4A-449B-9764-4B01C3D2A135](https://user-images.githubusercontent.com/46965981/90769966-178d7980-e2bf-11ea-9700-7df28784ebf0.jpeg)  

which ocvalidator doesn't see at all  
![D35B5E31-E807-4411-814B-0489147AE909](https://user-images.githubusercontent.com/46965981/90770020-2b38e000-e2bf-11ea-8d06-af24fe000e9b.jpeg)  

OC-tool will even automatically add or remove fields as needed if you want it to, so I'm wondering what the benefit of ocvalidator will be?

**Comment by HQuest** [comment]
Assuming the sample file is not manually changed, if you feel the sample to config comparison finds and reports all deviations and is kept updated with latest source files, then yes, it may be redundant and one opted over the other. Since this is the team’s official tool, it may save you some maintenance tasks - but ultimately I guess it is your choice.

Side note to avoid a new bug item: add support to VirtualSMC plugin SMCDellSensors.kext ;)

Thanks!

**Comment by rusty-bits** [comment]
I just saw the DellSensors issue, thanks  

for the time being, I'm going to leave OC-tool as is but am now thinking about adding support for ocvalidator to the new GUI version of OC-tool, if I ever get around to finishing it.  

any manual changes made to Sample.plist won't persist when OC-tool builds from source, it will throw up a message and replace it with the current Sample.plist   

any manual changes to the archived plists, e.g. Sample060.plist, won't persist through any update to OC-tool   

If I find that OC-tool is missing things that ocvalidator finds, or if you find that OC-tool is missing things please let me know, and I will consider adding it in, but I'm really at the point that I want to retire OC-tool and put my attention on octool, just haven't been able to find time to do much of anything on it lately  

Thank you!
