### ISSUE TITLE
VirtualSMC Dell sensors plug-in is missing

### ISSUE THREAD

**Issue by zearp** [rusty-bits/OC-tool#48]
Great work on this tool, didn't realise it existed and sure cleaned up my messy OC build folder. Currently the Dell sensors are missing. I added the following to *git_repo.json.txt* but that's probably too dirty and not enough for all use cases except when building from source.

```
| SMCDellSensors.kext|parent "VirtualSMC"
| SMCDellSensors.kext|path "Kexts"
```

I checked the others and this is the only missing VirtualSMC plug-in.

**Comment by rusty-bits** [comment]
gross Dell!  

jk, thanks, didn't even know that kext was in there.  
Added it to the json and json.txt file, should work fine now building an EFI from source, daily prebuilts, and release prebuilts.  

Thanks, again.
