### ISSUE TITLE
[Bug] Copying BOOTx64.efi Error

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#49]
Copying BOOTx64.efi Error
[tool.log](https://github.com/rusty-bits/OC-tool/files/5147938/tool.log)

<img width="722" alt="Screenshot 2020-08-31 at 02 51 10" src="https://user-images.githubusercontent.com/2873112/91675670-0e10d680-eb35-11ea-9af2-dfb48962e0a5.png">

**Comment by rusty-bits** [comment]
Thanks for the report, I probably wouldn't have noticed the issue for another day at least.
