### ISSUE TITLE
BOOTx64.efi compiled from source causing EFI partition to show in picker

### ISSUE THREAD

**Issue by zearp** [rusty-bits/OC-tool#51]
I'm not sure if 100% related to OC-tool, but when I compile from source using OC-tool the resulting BOOTx64.efi file will make the EFI partition show in the picker. If I use the BOOTx64.efi from an official release or the Dortania builds the EFI partition doesn't show in the picker. It's been a real head scratcher to me. Any ideas why this happens?

**Comment by rusty-bits** [comment]
Well, that's an odd one.  I could be doing something wrong in OC-tool, I'll have to take a peek when I can.   

Keep in mind, if you build from source, you are building OpenCore 0.6.2 right now.  There were some changes and BOOTx64.efi no longer exists.  It used to be that Bootstrap.efi was a copy of the BOOTx64.efi, but that changed in 0.6.2 and now BOOTx64.efi is a copy of Bootstrap.efi if you are building from source.

**Comment by rusty-bits** [comment]
I was wrong, just looked back at the change-logs and BOOTx64.efi changed in 0.6.1 so I probably need to change something in OC-tool since source and release should both be using Bootstrap.efi for BOOTx64.efi   

I'll try to get to this issue soon.

**Comment by zearp** [comment]
Thank you, no worries and no rush. Not a showstopper by any means. My uneducated guess is that it's probably a flag or option at compile time.

**Comment by rusty-bits** [comment]
Compile time flags used in OC-tool are the same as those used in the build_oc.tool from Acidanthera, so I don't think that was the issue.  I have fixed the code in OC-tool so it uses Bootstrap.efi in all cases as it should, and I am not seeing an EFI option appear in my picker, but I don't think I ever did.  If you're still seeing it then I may have to check for compile time variables that build_oc.tool may set that I don't.  Let me know if there is still an issue.

**Comment by zearp** [comment]
Thanks for checking! Updated and rebooted and the entry is still there, both using when -s and -d. Also tried starting from scratch with same result. It won't show when running OC-tool without any parameters. The current build on Dortania doesn't have the entry too. Not sure if their build system is open or if it's useful to compare. I have ScanPolicy set to 0 in my config.

**Comment by rusty-bits** [comment]
That might be why I don't see it, I don't have scan policy set to 0.  I'll take another look at it after I fix this other issue.

**Comment by amiles5** [comment]
I have had this issue for quite some time - at least since Opencore 5.9 ?? I thought it was just me with an incorrect config.plist?

**Comment by zearp** [comment]
Also recall its been happening for a while and also assumed it was just me. I think when they integrated the HideSelf option in 0.5.9 the EFI entry appeared in OC-tool builds.

**Comment by rusty-bits** [comment]
> I have had this issue for quite some time - at least since Opencore 5.9 ?? I thought it was just me with an incorrect config.plist? Still currently adding EFI option.

Nope, it looks like it's something I'm doing, I just never noticed it since I never have my ScanPolicy set to zero.  I may need to use the tool included in the OpenCorePkg to compile it so it will have the correct environment variables set.  Probably won't get to it until this weekend, though.

**Comment by menditsa** [comment]
Just to let you know this happens on Pavo's oc-builder tool too.

**Comment by rusty-bits** [comment]
Included Acidanthera Info in Bootstrap.efi build so OpenCore will now see and ignore BOOTx64.efi/Bootstrap.efi on the picker screen.   
Will require a rebuild of OpenCorePkg, you can ...   
wait for an update of OpenCore and the OpenCorePkg will rebuild automatically, or    
use the -X option to remove the resources/latestSource folder, or  
remove the resources folder in it's entirety.

**Comment by zearp** [comment]
Can confirm the entry no longer shows, thank you for fixing this so fast!

**Comment by zearp** [comment]
The EFI entry has returned.

> Placing Acidanthera Research (C) into Bootstrap.efi ... done

It's still doing that, maybe something has changed on their side?

Btw, thank you for implementing ```ocvalidate``` in OC-tool, such a great addition. I always forget that tool exists. Helped me find some things that weren't properly configured.

**Comment by rusty-bits** [comment]
I'll take a peek at it. I must have broken something when I put the code in for ocvalidate

**Comment by zearp** [comment]
No need, it was on my side only. I've edited my post as soon as I found out the issue was caused by me. But I think you don't get new emails when someone makes an edit.  It was caused by messed up NVRAM variables somehow. Most likely caused by me installing different version of macOS without clearing NVRAM in between. I'll do my walk of shame.

**Comment by zearp** [comment]
No need, it was on my side only. I've edited my post as soon as I found out the issue was caused by me. But I think you don't get new emails when someone makes an edit. It was caused by messed up NVRAM variables somehow. Most likely caused by me installing different versions of macOS without clearing NVRAM in between. I'll do my walk of shame.
