### ISSUE TITLE
Initial MacKernelSDK and Xcode 12 compatibility

### ISSUE THREAD

**Issue by menditsa** [rusty-bits/OC-tool#52]
Firstly thanks for the tool
vit9696 has introduced a commit **Initial MacKernelSDK and Xcode 12 compatibility** into his builds which now causes oc-tool to fail to build source builds and rollback to prior to this commit.

![Screenshot 2020-09-21 at 09 54 19](https://user-images.githubusercontent.com/3509336/93748624-77de4680-fbf0-11ea-87f8-62faf481eabf.png)

**Comment by rusty-bits** [comment]
Thanks for the info, looks like I have a bit of fixing to do.

**Comment by menditsa** [comment]
And confirmed working my end.
