### ISSUE TITLE
fatal: repository '' does not exist

### ISSUE THREAD

**Issue by HQuest** [rusty-bits/OC-tool#53]
While building OC from today' sources, OC-tool ended up with an invalid blank repository to work with. Logs attached (SN data removed for privacy).

[Archive.zip](https://github.com/rusty-bits/OC-tool/files/5276898/Archive.zip)

**Comment by rusty-bits** [comment]
Looks like it's failing on VoodooI2CHID   

OC-tool can't build VoodooI2C resources right now, different build process than everything else, so looks like the -d and -s options will fail    

Unfortunately, OC-tool doesn't know it can't build them.  It is seeing the prebuilt releases for VoodooI2C, but not checking if source files are available before it tries to build them.  I'll have to tag the VoodooI2C children in the json file somehow    

Thanks for finding this

**Comment by HQuest** [comment]
Always happy (and sorry) for keeping you busy ;)

**Comment by rusty-bits** [comment]
Don't be sorry, I'm thankful for those that find bugs, and I appreciate your suggestions for improvements, even if I can't implement them all.  
OC-tool should now correctly identify resources that it can not compile.  Maybe someday I'll figure out the I2C compile process and add that in as well.
