### ISSUE TITLE
ERROR: build failed for Lilu

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#54]
<img width="575" alt="Screenshot 2020-09-29 at 22 49 55" src="https://user-images.githubusercontent.com/2873112/94620421-82f73d80-02a6-11eb-8c80-2a0c91d43f2d.png">

[tool.log](https://github.com/rusty-bits/OC-tool/files/5302054/tool.log)

**Comment by menditsa** [comment]
Looking at the log:

xcode-select: error: **_tool 'xcodebuild' requires Xcode_**, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Seems to clearly explain why you have the failure.

**Comment by Blurayx** [comment]
Thanks for taking a look. How do I fix it?

Thanks

**Comment by rusty-bits** [comment]
`xcode-select -p`  will show the path the command line tools are using   

in your case it looks like you have it pointing at the tools themselves, not to xcode  

`sudo xcode-select -s /Applications/Xcode.app` will set the path to the Xcode app, assuming you have it in the Applications folder

**Comment by Blurayx** [comment]
problem solved. Thanks😀
