### ISSUE TITLE
OC-tool cannot build codeless BrcmBluetoohInjector

### ISSUE THREAD

**Issue by HQuest** [rusty-bits/OC-tool#55]
As stated on [BrcmPatchRAM](https://github.com/acidanthera/BrcmPatchRAM):

> The BrcmBluetoothInjector.kext is a codeless kernel extension which injects the BT hardware data using a plist; it does not contain a firmware uploader.

While this kext is added into a config.plist file, the OC-tool builds the main BrcmPatchRAM/RAM2/RAM3 kexts, but it does not build the codeless one. While it does not fail during build, it the fails to copy this file since it isn't there. Unsure if there is a specific xcodebuild required to create this kext or if a manual creation process is required (hint: the .plist file is available on the root folder of the BrcmPatchRAM sources).

**Comment by rusty-bits** [comment]
It looks like I made a change in May for BrcmPatchRAM to only build the requested kexts, instead of the whole repo.  Unfortunately I tagged the scheme of every kext as BrcmPatchRAM, so it was only building BrcmPatchRAM.kext no matter what was requested.  
Hopefully this fixes it.

**Comment by HQuest** [comment]
I will give it a go later this week - work has ramping up lately. I trust you already nailed it. Thank you once again for such great tool.
