### ISSUE TITLE
cannot deal with pipe symbol in comments ;-))

### ISSUE THREAD

**Issue by andistern** [rusty-bits/OC-tool#57]
just discovered: 
`sed: 11: comm.txt: bad flag in substitute command: 'H'`
```
cat INPUT/temp/comm.txt | head -11 | tail -1
s|ACPI_Patch_3|HPET _CRS to XCRS Rename  |HPET _CRS to XCRS Rename | (_CRS -&gt; (XCRS to be precise ;-))|
```

```
grep precise INPUT/config.plist 
				<string>HPET _CRS to XCRS Rename | (_CRS -&gt; (XCRS to be precise ;-))</string>
```
as workaround is obvious, please assign lowest possible priority!
regards 
A.

**Comment by rusty-bits** [comment]
oops, that's what happens when I use '|' as a delimiter in an attempt to fix other problems   
should be an easy enough fix

**Comment by rusty-bits** [comment]
for now I will have OC-tool replace any pipe character with a '!' to avoid parsing problems, I will try to come up with something more elegant that doesn't change the comments in the future

**Comment by andistern** [comment]
good to know, that using exclamation marks in comments could be dangerous!
thanks a lot!
