### ISSUE TITLE
OpenCorePkg

### ISSUE THREAD

**Issue by menditsa** [rusty-bits/OC-tool#58]
Since todays update I'm getting this fail error when trying to retrieve OpenCorePkg

**/usr/bin/plutil
/Users/menditsa/Desktop/OC-tool/INPUT/temp/config.plist.tmp: OK
fatal: no path specified; see 'git help pull' for valid url syntax**

**Comment by rusty-bits** [comment]
sorry about that, made some changes but didn't check them on multiple shells  

should be all set now, but you may have to run `git pull` manually to get the update the first time
