### ISSUE TITLE
[Bug]Stuck downloading Hfs.plus

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#59]
Stuck downloading Hfs.plus

After 10miuntes OC-tool still trying to download Hfs.plus
<img width="702" alt="Screenshot 2020-12-05 at 02 34 16" src="https://user-images.githubusercontent.com/2873112/101231457-52b38d00-36a3-11eb-97d8-6a9bfd35205d.png">

[tool.log.zip](https://github.com/rusty-bits/OC-tool/files/5646377/tool.log.zip)

Thanks

**Comment by rusty-bits** [comment]
It helps if I don't push code that I was using for debugging.  Thanks for the report.

**Comment by Blurayx** [comment]
> It helps if I don't push code that I was using for debugging. Thanks for the report.

🤣
