### ISSUE TITLE
no building

### ISSUE THREAD

**Issue by locussss** [rusty-bits/OC-tool#6]
Hi, OC-tool does't do anything:

./OC-tool -sv ./extras/config.plist
For help use './OC-tool -h'

Using ./extras/config.plist

Checking for updates ... 
OC-tool - OK

Checking existing resources ... 
/usr/bin/xcodebuild
/usr/local/bin/nasm
/usr/local/bin/mtoc
locus@locus OC-tool % 

That's all!

source is from today an hour ago....

**Comment by rusty-bits** [comment]
I found 'A' problem, but I don't know if it will fix 'THE' problem.  
More accurately, I had messed up the code that checks if INPUT/config.plist exists or not, but that shouldn't affect you since you are providing a path to a config.plist when you run.  

I moved my config from `INPUT` to `extras` temporarily to see if I had the same problem, but I don't.  It still built fine for me.  

A few of questions to start ...  
1) Why do you have a config.plist in the `extras` directory?  It's not wrong, exactly, but OC-tool looks in the `INPUT` folder by default for a config.plist.  

2)Do you see any error message in the tool.log file? It should be the same as the verbose output with the -v option, but I might have errors directed to tool.log only.  

3)What do you see with the -t option?  You can try `./OC-tool -st ./extras/config.plist` or just `./OC-tool -st` if your config.plist is in the `INPUT` folder.  

let me know what you find and I'll see what I can fix

**Comment by locussss** [comment]
1. I have everything in extra because there are all my kexts and efi's to be included in the EFI folder which aren't build by OC-tool and I like config.plist to be there too, just a choice

2. tool.log 
only these three lines...
/usr/bin/xcodebuild
/usr/local/bin/nasm
/usr/local/bin/mtoc

3.
The result:

locus@locus OC-tool % ./OC-tool -st ./extras/config.plist
For help use './OC-tool -h'

Using ./extras/config.plist

Checking for updates ... 
OC-tool - updated

INFO: OC-tool has been updated, run tool again to continue
locus@locus OC-tool % ./OC-tool -st ./extras/config.plist
For help use './OC-tool -h'

Using ./extras/config.plist

Checking for updates ... 
OC-tool - OK

Checking existing resources ... 
locus@locus OC-tool %

**Comment by rusty-bits** [comment]
try this while I check on a couple of things  

`./OC-tool -n ./extras/config.plist`

**Comment by locussss** [comment]
locus@locus OC-tool % ./OC-tool -n ./extras/config.plist
To build from source use -s option
For help use './OC-tool -h'

Using ./extras/config.plist
locus@locus OC-tool % 

Nothing...

**Comment by rusty-bits** [comment]
Well, that's very odd that you get nothing with that.  I just remoted in to a few of my servers and tried OC-tool on them, no issues. Hmm, I wonder if I broke something that affects something unique to your setup.  

Give me about 30 minutes, I'm going to add debug output to OC-tool so we can see exactly where it is dying.  If whatever I did is affecting you it could be broken for others, too.  

While I do that, try this if you can, it might help me rule out a few things to find what I broke  

`./OC-tool ./Docs/Sample.plist`

**Comment by locussss** [comment]
Here it is...

locus@locus OC-tool % ./OC-tool ./Docs/Sample.plist          
To build from source use -s option
For help use './OC-tool -h'

Using ./Docs/Sample.plist

Checking for updates ... 
OC-tool - OK

Downloading/unzipping needed or updated resources
Downloading OpenCore-0.5.3-DEBUG.zip ... unzipping ... done
Downloading Lilu-1.4.0-DEBUG.zip ... unzipping ... done
Downloading VirtualSMC-1.0.9-DEBUG.zip ... unzipping ... done
Downloading WhateverGreen-1.3.5-DEBUG.zip ... unzipping ... done
Downloading AppleALC-1.4.4-DEBUG.zip ... unzipping ... done
Downloading HFSPlus.efi ... unzipping ... done
Downloading AppleSupport-2.1.4-DEBUG.zip ... unzipping ... done

Creating new /Users/locus/Documents/OC-tool/OUTPUT/EFI ... done

Moving prebuiltRelease resources into place
Copying BOOTx64.efi to BOOT ... done
Copying OpenCore.efi to OC ... done
Copying config.plist to OC ... done
Copying Lilu.kext to OC/Kexts ... done
Copying VirtualSMC.kext to OC/Kexts ... done
Copying WhateverGreen.kext to OC/Kexts ... done
Copying AppleALC.kext to OC/Kexts ... done
Copying HfsPlus.efi to OC/Drivers ... done
Copying ApfsDriverLoader.efi to OC/Drivers ... done
Copying FwRuntimeServices.efi to OC/Drivers ... done
Copying VirtualSmc.efi to OC/Drivers ... done

Building vault files for /Users/locus/Documents/OC-tool/OUTPUT/EFI ... ERROR: vault build failed, see /Users/locus/Documents/OC-tool/tool.log for details
locus@locus OC-tool %

**Comment by rusty-bits** [comment]
hmm, it's starting to look like your config.plist has a problem   
OC-tool doesn't do a validity check on it, but it should still give some kind of error   

I've added a little debug info, try this ...   

`git checkout consistent`   
`git pull`   
`./OC-tool -sD ./extras/config.plist`   
this should show where it is dying, and if I broke something it should point the way      

also try this   
`plutil ./extras/config.plist`   
this checks if the plist structure is valid, but doesn't mean there aren't other errors

**Comment by locussss** [comment]
First step
locus@locus OC-tool % git checkout consistent
D	INPUT/readme.txt
D	LICENSE
D	OUTPUT/readme.txt
D	README.md
D	extras/README.txt
Branch 'consistent' set up to track remote branch 'consistent' from 'origin'.
Switched to a new branch 'consistent'
locus@locus OC-tool % git pull
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/rusty-bits/OC-tool
   20751ea..5483b0f  consistent -> origin/consistent
Updating 20751ea..5483b0f
Fast-forward
 OC-tool | 19 +++++++++++++++----
 1 file changed, 15 insertions(+), 4 deletions(-)
locus@locus OC-tool % ./OC-tool -sD ./extras/config.plist

db - start logging

db - filePath ./extras/config.plist CONFIG_PLIST /Users/locus/Documents/OC-tool/INPUT/temp/config.plist
For help use './OC-tool -h'

Using ./extras/config.plist

Checking for updates ... 
OC-tool - OK

Checking existing resources ... 

db - MODE latestSource TYPE debug UNAME Darwin

db - no-pre-base ... done

db - pre-base ... done

db - init_res_array ... done

db - add ACPI ... done

db - add Kernel ... done

db - add Drivers ... done
locus@locus OC-tool % 

Second step
locus@locus OC-tool % plutil ./extras/config.plist
./extras/config.plist: OK
locus@locus OC-tool %

**Comment by locussss** [comment]
In config.plist I have changed Kernel/Quirks/ThirdPartyDrives as Boolean, before that was ThirdPartyTrim but that is according to Differences.pdf.....

**Comment by rusty-bits** [comment]
yeah, vit removed ThirdPartyTrim about a week ago, ThirdPartyDrives is the right one now.   

OC-tool should have read your Tools section after the Drivers section, but it died before it finished Tools.   

What does your Tools section look like in `./extras/config.plist` ?

**Comment by locussss** [comment]
Okay, I had disabled them with #Tools and that was the culprit but the  strange thing is that it has been like that for not ages but a long time and before I didn't have this problem of not building.

But for now I have removed the # and enabled Tools and the building continues without error!

Sorry for this noise!

 Do I have to reverse some of your commands with git?

**Comment by rusty-bits** [comment]
first, don't be sorry, I've changed some of the loops in OC-tool to prepare for the prebuiltDaily option   
I never took a missing config.plist section into account, I'll have to do something about that.   

you can type   
`git checkout master`   
to get back to the main tool   

now, I'm off to break more stuff!!   

thanks for the report
