### ISSUE TITLE
OpenHfsPlus.efi is not recognized as a built-in binary

### ISSUE THREAD

**Issue by bkmartin** [rusty-bits/OC-tool#60]
ERROR:	OpenHfsPlus.efi - no prebuilt found for OpenHfsPlus.efi
	OpenHfsPlus.efi file not found in extras directory

OpenCore 0.6.6 added OpenHfsPlus.efi as a built-in binary, but it is not yet recognized by OC-tool, so you need to copy to extras to use it with OC-tool.  Would be great to have this binary recognized as prebuilt

**Comment by rusty-bits** [comment]
oops, I didn't add in the new additions.  I'll add them in, take about an hour or so

**Comment by bkmartin** [comment]
thanks.... I think you need to add OpenPartitionDxe.efi as well.  I should have mentioned this in the original issue

**Comment by bkmartin** [comment]
btw, I love this tool.  thanks for maintaining it

**Comment by rusty-bits** [comment]
glad you love it  

It looks like I'm missing more than OpenPartitionDxe.efi as well, I'll need to go through the OpenCorePkg and see what else I'm missing.  I need to write a tool to keep my tool up to date!
