### ISSUE TITLE
[Bug] ERROR:	build failed for Lilu

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#61]
[tool.log](https://github.com/rusty-bits/OC-tool/files/6066759/tool.log)

<img width="586" alt="Screenshot 2021-03-02 at 07 13 12" src="https://user-images.githubusercontent.com/2873112/109612054-0f907b00-7b27-11eb-89e6-3795075b8289.png">

Thanks

**Comment by rusty-bits** [comment]
Hey Blurayx,  
  I have no remote access to my dev machine at the moment to check this.  Do you get the same behavior if you try `./OC-tool -sX`

**Comment by Blurayx** [comment]
> Hey Blurayx,
> I have no remote access to my dev machine at the moment to check this. Do you get the same behavior if you try `./OC-tool -sX`

Yes

**Comment by rusty-bits** [comment]
Thanks, I'll give it a check as soon as I can.  It's also odd that your OC-tool isn't seeing the latest 74abadd commit of Lilu, only the one from Jan 8th   
  
oh, nevermind, the latest Lilu is only from two hours ago.  I'll check when I can

**Comment by Blurayx** [comment]
Thanks😀

**Comment by rusty-bits** [comment]
finally got remote access, not seeing any immediate trouble  
![5D1083D1-64EA-4BE8-904C-EC36F0602ECB](https://user-images.githubusercontent.com/46965981/109698652-9f511c00-7b5d-11eb-81b2-682d49f90b4d.jpeg)

can I see the tail end of your tool.log and update.log if possible and I'll look into it when I get home?

**Comment by Blurayx** [comment]
[tool.log](https://github.com/rusty-bits/OC-tool/files/6071135/tool.log)
[update.log](https://github.com/rusty-bits/OC-tool/files/6071136/update.log)

**Comment by rusty-bits** [comment]
from the tool.log it looks like your path to Xcode from the command line is not pointing to Xcode  
`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`  

you can check by trying  
`xcode-select -p`  
to see what path xcodebuild is using, it should be pointing to something like `/Applications/Xcode.app/Contents/Developer`  
  
if it isn't you can set it with  
`sudo _ xcode-select -s /Applications/Xcode.app/`   
  
this kind of thing can happen if Xcode or the CommandLineTools were updated

**Comment by Blurayx** [comment]
Entering the command line "sudo xcode-select -s /Applications/Xcode.app/" fixed the issue 😀

Thank you so much.

**Comment by rusty-bits** [comment]
glad you're all set
