### ISSUE TITLE
[Bug] Error

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#63]
Getting 3 errors but still generates an EFI folder

[tool.log](https://github.com/rusty-bits/OC-tool/files/6255484/tool.log)

![Screenshot 2021-04-04 at 23 27 39](https://user-images.githubusercontent.com/2873112/113523232-724dba00-959e-11eb-945d-7cdc8805856b.jpeg)

Thanks

**Comment by rusty-bits** [comment]
That's not a bug. That is the output of the ocvalidate tool from Acidanthera, your config.plist has errors, for example you are missing the UEFI>AppleInput section.  OC-tool can't automatically update everything in the config.plist unless I include the section for it to check.  
  
I have added awareness of that section to OC-tool in 6010f48 which should let it add the section.  As long as UEFI>AppleInput is in the 0.6.8 release there shouldn't be a problem.

**Comment by Blurayx** [comment]
Thank You😀
