### ISSUE TITLE
Add support for BlueToolFixup kext off BrcmPatchRAM

### ISSUE THREAD

**Issue by HQuest** [rusty-bits/OC-tool#67]
New on macOS12 Monterey Jack Cheese are modified functions on Bluetooth stack that BrcmBluetoothInjection is unable to fix (https://github.com/acidanthera/bugtracker/issues/1669). OC-tool can build the new BlueToolFixup.kext with the following addition to the git_repo.json file:

> |BlueToolFixup.kext|buildScheme "BlueToolFixup"
> |BlueToolFixup.kext|parent "BrcmPatchRAM"
> |BlueToolFixup.kext|path ""

See https://github.com/acidanthera/BrcmPatchRAM#bluetoolfixupkext for more.

**Comment by rusty-bits** [comment]
Thank you for the info, I'll add it in when I get a bit of free time.

**Comment by rusty-bits** [comment]
All set, BlueToolFixup added to json + json.txt file
Thank you
