### ISSUE TITLE
[Bug] Not updating to 0.7.1

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#68]
OC-tool not updating to the latest release 0.7.1

<img width="1048" alt="Screenshot 2021-07-06 at 01 28 25" src="https://user-images.githubusercontent.com/2873112/124526086-8dc49d00-ddf9-11eb-9614-5abada861c8b.png">

[tool.log](https://github.com/rusty-bits/OC-tool/files/6766541/tool.log)

Thanks

**Comment by rusty-bits** [comment]
well, not really a bug, I'm just slow
almost done testing on my end, I'll push the update soon

**Comment by Blurayx** [comment]
Ah, sorry!!

Thanks for the quick response😀

**Comment by rusty-bits** [comment]
Don't be sorry, some times I get lost in my own little world :)

**Comment by Blurayx** [comment]
updated to 0.7.1. no issues 

Thanks 😀
