### ISSUE TITLE
build failed for IntelMausi

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#71]
Hi
Previously I have never needed to add IntelMausi to the extras folder. Do know why?

<img width="973" alt="Screenshot 2021-09-07 at 02 33 46" src="https://user-images.githubusercontent.com/2873112/132271281-41d2bc56-9e77-483b-8501-6be3eb235009.png">

[tool.log](https://github.com/rusty-bits/OC-tool/files/7118336/tool.log)

Thanks

**Comment by Blurayx** [comment]
Update

After adding IntelMausi to the extra folder. oc-tool kept returning errors to add AppleALC, Lilu, WhateverGreen, and VirtualSMC. When I added VirtualSMC oc-tool still returned an error

<img width="973" alt="Screenshot 2021-09-07 at 02 57 11" src="https://user-images.githubusercontent.com/2873112/132272990-90af314d-ddb1-4128-9094-17a1419ce8e9.png">

[tool.log](https://github.com/rusty-bits/OC-tool/files/7118411/tool.log)


Thanks

**Comment by rusty-bits** [comment]
hmm, it looks like OC-tool thinks some part of the build tool is there, but it isn't  
what happens if you run ./OC-tool -Xs or if you manually remove the resources folder and run ./OC-tool -s

**Comment by Blurayx** [comment]
Both configurations returned failed to build.

 tool.log

**Comment by rusty-bits** [comment]
from the looks of your log, you may have updated xcode recently but didn't update the command line tool path to point to the Xcode App

`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

**Comment by rusty-bits** [comment]
might need something like this  
`sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer`  
or just Xcode.app if you're not using the latest beta Xcode

**Comment by Blurayx** [comment]
Deleted Xcode beta. Reinstalled the Offical release Xcode. Applied the command line "sudo xcode-select -s /Applications/Xcode.app/Contents/Developer".  worked!!!

[tool.log](https://github.com/rusty-bits/OC-tool/files/7121709/tool.log)

Thanks
