### ISSUE TITLE
OpenCanopy.efi issues

### ISSUE THREAD

**Issue by ArchCryptonIO** [rusty-bits/OC-tool#72]
Hello there, i'm using your tool since OC 0.6.8. I realise OpenCanopy.efi generated by your tool has an issue because 0.7.3 release, boot menu back to built-in. I change OpenCanopy.efi using official release by Acidanthera and it works again. I mention it because i love your tool. Easy for me to update and maintain my EFI.

Thank you.

**Comment by rusty-bits** [comment]
I'm not sure I know what you mean by the OpenCanopy.efi generated by OC-tool  
If you're telling OC-tool to use the current release (with no command line options) then OC-tool will use the release efi from Acidanthera (or it should, is this the issue you're having?)      
  
If you're telling OC-tool to build from source (with the -s option) then you are building version 0.7.4 prerelease files, not much that OC-tool can do to fix that, Acidanthera will have to fix the source code  
  
Could you give me more info to better describe the trouble you're having?

**Comment by ArchCryptonIO** [comment]
Forget that sir, thank you for reply. Everything is solved now. I appreciate it you concern. Thank you so much for build this tools.
