### ISSUE TITLE
not all EFI drivers loaded in 0.7.3 release

### ISSUE THREAD

**Issue by bkmartin** [rusty-bits/OC-tool#73]
I've been using this tool for quite some time, but when trying to update to 0.7.3, not all of my drivers in the config.plist are being loaded...

Here is the output

Moving prebuiltRelease resources into place
Copying BOOTx64.efi to BOOT/BOOTx64.efi ... done
Copying OpenCore.efi to OC/OpenCore.efi ... done
Copying config.plist to OC/config.plist ... done
Copying SSDT-USBX.aml from extras to OC/ACPI/SSDT-USBX.aml ... done
Copying SSDT-PLUG-DRTNIA.aml from extras to OC/ACPI/SSDT-PLUG-DRTNIA.aml ... done
Copying SSDT-EC.aml from extras to OC/ACPI/SSDT-EC.aml ... done
Copying Lilu.kext to OC/Kexts/Lilu.kext ... done
Copying VirtualSMC.kext to OC/Kexts/VirtualSMC.kext ... done
Copying AppleALC.kext to OC/Kexts/AppleALC.kext ... done
Copying IntelMausi.kext to OC/Kexts/IntelMausi.kext ... done
Copying SMCProcessor.kext to OC/Kexts/SMCProcessor.kext ... done
Copying SMCSuperIO.kext to OC/Kexts/SMCSuperIO.kext ... done
Copying USBMap.kext from extras to OC/Kexts/USBMap.kext ... done
Copying WhateverGreen.kext to OC/Kexts/WhateverGreen.kext ... done
Copying OpenShell.efi to OC/Tools/OpenShell.efi ... done

Copied 15 resources to /Users/bkmartin/opencore/OC-tool/OUTPUT/EFI

If I run in TUI mode and press "p", I see the following output, but not all of these drivers are copied as seen above (e.g. OpenRuntime, OpenCanopy, OpenHfsPlus)

Processing config.plist ... done
Checking for missing fields ... done
Checking for extra fields ... done
Using /Users/bkmartin/opencore/OC-tool/INPUT/config.plist

Switching to TUI ... 
00|BOOTx64.efi|X64/EFI/BOOT|-|BOOT|OpenCorePkg|true
01|OpenCore.efi|X64/EFI/OC|-|OC|OpenCorePkg|true
02|config.plist||/Users/bkmartin/opencore/OC-tool/INPUT/temp|OC||true
10|SSDT-USBX.aml||/Users/bkmartin/opencore/OC-tool/extras|OC/ACPI||6
11|SSDT-PLUG-DRTNIA.aml|raw/master/extra-files/compiled|/Users/bkmartin/opencore/OC-tool/extras|OC/ACPI|Getting-Started-With-ACPI|10
12|SSDT-EC.aml||/Users/bkmartin/opencore/OC-tool/extras|OC/ACPI||14
20|Lilu.kext||-|OC/Kexts|Lilu|139
21|VirtualSMC.kext|Kexts|-|OC/Kexts|VirtualSMC|148
22|AppleALC.kext||-|OC/Kexts|AppleALC|157
23|IntelMausi.kext||-|OC/Kexts|IntelMausi|166
24|SMCProcessor.kext|Kexts|-|OC/Kexts|VirtualSMC|175
25|SMCSuperIO.kext|Kexts|-|OC/Kexts|VirtualSMC|184
26|USBMap.kext||/Users/bkmartin/opencore/OC-tool/extras|OC/Kexts||193
27|WhateverGreen.kext||-|OC/Kexts|WhateverGreen|202
30|OpenRuntime.efi|X64/EFI/OC/Drivers|-|OC/Drivers|OpenCorePkg|491
31|OpenCanopy.efi|X64/EFI/OC/Drivers|-|OC/Drivers|OpenCorePkg|492
32|AudioDxe.efi|X64/EFI/OC/Drivers|-|OC/Drivers|OpenCorePkg|493
33|NvmExpressDxe.efi|X64/EFI/OC/Drivers|-|OC/Drivers|OpenCorePkg|494
34|OpenHfsPlus.efi|X64/EFI/OC/Drivers|-|OC/Drivers|OpenCorePkg|495
40|OpenShell.efi|X64/EFI/OC/Tools|-|OC/Tools|OpenCorePkg|390
G1 5
G2 138
G3 490
G4 389
G5 79
G6 312
G7 538
G8 109
TOT 567

**Comment by rusty-bits** [comment]
Do you have "Enabled: true" set on all of them?

**Comment by bkmartin** [comment]
I looked at the Open Core configuration.pdf and I don't see an enabled section for UEFI->Drivers

`        <key>UEFI</key>
        <dict>
                <key>APFS</key>
                <dict>
                        <key>EnableJumpstart</key>
                        <true/>
                        <key>GlobalConnect</key>
                        <false/>
                        <key>HideVerbose</key>
                        <true/>
                        <key>JumpstartHotPlug</key>
                        <false/>
                        <key>MinDate</key>
                        <integer>0</integer>
                        <key>MinVersion</key>
                        <integer>0</integer>
                </dict>
                <key>AppleInput</key>
                <dict>
                        <key>AppleEvent</key>
                        <string>Builtin</string>
                        <key>CustomDelays</key>
                        <false/>
                        <key>GraphicsInputMirroring</key>
                        <true/>
                        <key>KeyInitialDelay</key>
                        <integer>0</integer>
                        <key>KeySubsequentDelay</key>
                        <integer>5</integer>
                        <key>PointerSpeedDiv</key>
                        <integer>1</integer>
                        <key>PointerSpeedMul</key>
                        <integer>1</integer>
                </dict>
                <key>Audio</key>
                <dict>
                        <key>AudioCodec</key>
                        <integer>0</integer>
                        <key>AudioDevice</key>
                        <string>PciRoot(0x0)/Pci(0x1F,0x3)</string>
                        <key>AudioOut</key>
                        <integer>1</integer>
                        <key>AudioSupport</key>
                        <true/>
                        <key>MinimumVolume</key>
                        <integer>70</integer>
                        <key>PlayChime</key>
                        <string>Auto</string>
                        <key>ResetTrafficClass</key>
                        <false/>
                        <key>SetupDelay</key>
                        <integer>0</integer>
                        <key>VolumeAmplifier</key>
                        <integer>120</integer>
                </dict>
                <key>ConnectDrivers</key>
                <true/>
                <key>Drivers</key>
                <array>
                        <string>OpenRuntime.efi</string>
                        <string>OpenCanopy.efi</string>
                        <string>AudioDxe.efi</string>
                        <string>NvmExpressDxe.efi</string>
                        <string>OpenHfsPlus.efi</string>
                </array>
...`

**Comment by rusty-bits** [comment]
I see it in the Configuration.pdf in Section 11.11 on page 85   
the Sample.plist has it as well  
```
               <key>Drivers</key>                                                                                       
                <array>                                                                                                  
                        <dict>                                                                                           
                                <key>Path</key>                                                                          
                                <string>HfsPlus.efi</string>                                                             
                                <key>Enabled</key>                                                                       
                                <true/>                                                                                  
                                <key>Arguments</key>                                                                     
                                <string></string>                                                                        
                        </dict> 
                        <dict>  
                                <key>Path</key>
                                <string>OpenRuntime.efi</string>
                                <key>Enabled</key>
                                <true/>
                                <key>Arguments</key>
                                <string></string>
                        </dict> 
                        <dict>  
                                <key>Path</key>
                                <string>OpenCanopy.efi</string>
                                <key>Enabled</key>
                                <false/>
                                <key>Arguments</key>
                                <string></string>
                        </dict> 
                        <dict>  .........
```

and OC-tool should have shown errors when it ran ocvalidate on the plist as well, probably something like unable to serialize array or something like that.  Were there no errors from ocvalidate?

**Comment by rusty-bits** [comment]
I just ran your config.plist just to make sure, and I see the errors on my end   
```
OCS: Couldn't get array serialized at 0 index!                                                                           
OCS: Couldn't get array serialized at 1 index!                                                                           
OCS: Couldn't get array serialized at 2 index!                                                                           
OCS: Couldn't get array serialized at 3 index!                                                                           
OCS: Couldn't get array serialized at 4 index!                                                                           
Serialisation returns 5 errors!
```

You need to fix your UEFI>Drivers section

**Comment by bkmartin** [comment]
sorry for bothering you, i missed that Drivers change in the update section...

**Comment by rusty-bits** [comment]
not a problem, just wanted to make sure the tool was working okay
