### ISSUE TITLE
Driver folder missing

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/OC-tool#75]
Drive folderr missing from EFI output folder.

Output
<img width="1024" alt="Screenshot 2021-10-02 at 09 07 48" src="https://user-images.githubusercontent.com/2873112/135708944-c6bd4437-bc38-45a4-89f7-ab4d4b2e8a76.png">

<img width="1017" alt="Screenshot 2021-10-02 at 09 07 23" src="https://user-images.githubusercontent.com/2873112/135708950-e8a22081-1094-4c0c-b85e-64a5ebfc2e21.png">

[tool.log](https://github.com/rusty-bits/OC-tool/files/7271106/tool.log)

Thanks

**Comment by rusty-bits** [comment]
compare your UEFI->Drivers section to the Sample.plist and fix your confg.plist   
the ocvalidate check even shows you have 5 issues in you config.plist

**Comment by Blurayx** [comment]
Reconfigured my plist from scratch. working perfectly no errors 😀

My original plist must have been corrupted at some point because after correcting the issues I was still getting errors.
For some reason, I wasn't having booting issues the corrupted plist

<img width="1178" alt="Screenshot 2021-10-03 at 02 36 05" src="https://user-images.githubusercontent.com/2873112/135736686-1cd5efb4-7c50-471d-a6da-51f9984797c3.png">

**Comment by Blurayx** [comment]
update:
when I add HfsPlus.efi I get the error.
[tool.log](https://github.com/rusty-bits/OC-tool/files/7272606/tool.log)

**Comment by Blurayx** [comment]
Update.
For some reason, ProperTree is corrupting my config.plist

**Comment by rusty-bits** [comment]
weird that you didn't have booting issues with the corrupted plist, but glad you have it all working  
also, you may want to start using the new [octool](https://github.com/rusty-bits/octool) since I don't think I'll be updating this older version that much

**Comment by Blurayx** [comment]
I tried octool a few weeks ago. unfortunately, I could get it to work. For now, I'll carry on using oc-tool while it's still working for me.
