### ISSUE TITLE
Shell.efi not copied - GUID labeled file

### ISSUE THREAD

**Issue by HQuest** [rusty-bits/OC-tool#8]
While building OC from sources (as of Jan 7 2020), the tool failed to copy Shell.efi as it searches for a GUID labeled file (from SHELL_EFI var) versus the plain "Shell.efi" file as specified on the config.plist Tools section.

However, by removing previous OC sources (i.e., by adding -X parameter) and building it from scratch, the build is completed successfully. See below for output examples.

Therefore, it might be a good idea to enforce/suggest -X parameter if the OC-tool script is updated. May not be needed at every single update, but for significant changes its usage/recommendation is likely welcome.

% ./OC-tool -s INPUT/config.debug.plist
For help use './OC-tool -h'

Using INPUT/config.debug.plist

Checking for updates ... 
OC-tool - OK

Checking Lilu ... 
Lilu updated to 2183e2a
All kexts will be rebuilt

Checking other existing resources ... 
AppleSupportPkg - updated to 4cf2aea
OcSupportPkg - updated to c1c72c0
EfiPkg - updated to 326650b
MacInfoPkg - updated to 0a66205
OpenCorePkg - updated to 596836f
existing resources have been updated

Building new or updated resources
Making base tools ... done
Building DEBUG MacInfoPkg ... done
Building DEBUG OcSupportPkg ... done
Building DEBUG OpenCorePkg ... done
Cloning https://github.com/acidanthera/Lilu into Lilu ... done
Building DEBUG Lilu ... done
Cloning https://github.com/acidanthera/VirtualSMC into VirtualSMC ... done
Building DEBUG VirtualSMC ... done
Cloning https://github.com/acidanthera/AppleALC into AppleALC ... done
Building DEBUG AppleALC ... done
Cloning https://github.com/acidanthera/WhateverGreen into WhateverGreen ... done
Building DEBUG WhateverGreen ... done
Cloning https://github.com/acidanthera/IntelMausi into IntelMausi ... done
Building DEBUG IntelMausi ... done
Building DEBUG AppleSupportPkg ... done
Building DEBUG AppleSupportPkg ... done
Making audk BaseTools for Shell.efi ... done
Patching audk for Shell.efi ... done
Building DEBUG Shell.efi (Shell_EA4BB293-2D7F-4456-A681-1F22F42CD0BC.efi) ... done

Removing old /Users/hquest/Downloads/OC-tool/OUTPUT/EFI ... done
Creating new /Users/hquest/Downloads/OC-tool/OUTPUT/EFI ... done

Moving latestSource resources into place
Copying BOOTx64.efi to BOOT ... done
Copying OpenCore.efi to OC ... done
Copying config.plist to OC ... done
Copying SSDT-XOSI.aml to OC/ACPI ... done
Copying SSDT-USBX.aml to OC/ACPI ... done
Copying SSDT-EC.aml to OC/ACPI ... done
Copying Lilu.kext to OC/Kexts ... done
Copying VirtualSMC.kext to OC/Kexts ... done
Copying AppleALC.kext to OC/Kexts ... done
Copying WhateverGreen.kext to OC/Kexts ... done
Copying AGPMInjector.kext to OC/Kexts ... done
Copying USBPorts.kext to OC/Kexts ... done
Copying IntelMausi.kext to OC/Kexts ... done
Copying SMCProcessor.kext to OC/Kexts ... done
Copying SMCSuperIO.kext to OC/Kexts ... done
Copying VBoxHfs.efi to OC/Drivers ... done
Copying ApfsDriverLoader.efi to OC/Drivers ... done
Copying FwRuntimeServices.efi to OC/Drivers ... done
Copying Shell.efi to OC/Tools ... 

ERROR: Copying Shell_EA4BB293-2D7F-4456-A681-1F22F42CD0BC.efi to OC/Tools failed, see /Users/hquest/Downloads/OC-tool/tool.log for details.
% ./OC-tool -X -s INPUT/config.debug.plist 
For help use './OC-tool -h'

Using INPUT/config.debug.plist

Checking for updates ... 
OC-tool - OK

Checking Lilu ... 
no existing Lilu found
Any existing kexts will be rebuilt to insure they are current

Checking other existing resources ... 

 *** WARNING: -X option used ****************************************
 *** /Users/hquest/Downloads/OC-tool/resources/latestSource has been removed
 *** the -X option is only useful if there is an issue with the
 *** previously downloaded resources causing problems while building.
 *** Using it at any other time will only increase bandwith usage and
 *** compile time, in many cases requiring all tools to be rebuilt.
 *********************************************************************

Building new or updated resources
Cloning https://github.com/acidanthera/audk into UDK ... done
Cloning https://github.com/acidanthera/EfiPkg into EfiPkg ... done
Cloning https://github.com/acidanthera/MacInfoPkg into MacInfoPkg ... done
Making base tools ... done
Building DEBUG MacInfoPkg ... done
Cloning https://github.com/acidanthera/OcSupportPkg into OcSupportPkg ... done
Building DEBUG OcSupportPkg ... done
Cloning https://github.com/acidanthera/OpenCorePkg into OpenCorePkg ... done
Building DEBUG OpenCorePkg ... done
Cloning https://github.com/acidanthera/Lilu into Lilu ... done
Removing Xcode DerivedData for Lilu ... done
Building DEBUG Lilu ... done
Cloning https://github.com/acidanthera/VirtualSMC into VirtualSMC ... done
Removing Xcode DerivedData for VirtualSMC ... done
Building DEBUG VirtualSMC ... done
Cloning https://github.com/acidanthera/AppleALC into AppleALC ... done
Removing Xcode DerivedData for AppleALC ... done
Building DEBUG AppleALC ... done
Cloning https://github.com/acidanthera/WhateverGreen into WhateverGreen ... done
Removing Xcode DerivedData for WhateverGreen ... done
Building DEBUG WhateverGreen ... done
Cloning https://github.com/acidanthera/IntelMausi into IntelMausi ... done
Removing Xcode DerivedData for IntelMausi ... done
Building DEBUG IntelMausi ... done
Removing Xcode DerivedData for VirtualSMC ... done
Removing Xcode DerivedData for VirtualSMC ... done
Cloning https://github.com/acidanthera/AppleSupportPkg into AppleSupportPkg ... done
Building DEBUG AppleSupportPkg ... done
Cloning https://github.com/acidanthera/OpenCoreShell into OpenCoreShell ... done
Cloning https://github.com/acidanthera/audk -b master --depth=1 into UDK ... done
Making audk BaseTools for Shell.efi ... done
Patching audk for Shell.efi ... done
Building DEBUG Shell.efi (Shell_EA4BB293-2D7F-4456-A681-1F22F42CD0BC.efi) ... done

Removing old /Users/hquest/Downloads/OC-tool/OUTPUT/EFI ... done
Creating new /Users/hquest/Downloads/OC-tool/OUTPUT/EFI ... done

Moving latestSource resources into place
Copying BOOTx64.efi to BOOT ... done
Copying OpenCore.efi to OC ... done
Copying config.plist to OC ... done
Copying SSDT-XOSI.aml to OC/ACPI ... done
Copying SSDT-USBX.aml to OC/ACPI ... done
Copying SSDT-EC.aml to OC/ACPI ... done
Copying Lilu.kext to OC/Kexts ... done
Copying VirtualSMC.kext to OC/Kexts ... done
Copying AppleALC.kext to OC/Kexts ... done
Copying WhateverGreen.kext to OC/Kexts ... done
Copying AGPMInjector.kext to OC/Kexts ... done
Copying USBPorts.kext to OC/Kexts ... done
Copying IntelMausi.kext to OC/Kexts ... done
Copying SMCProcessor.kext to OC/Kexts ... done
Copying SMCSuperIO.kext to OC/Kexts ... done
Copying VBoxHfs.efi to OC/Drivers ... done
Copying ApfsDriverLoader.efi to OC/Drivers ... done
Copying FwRuntimeServices.efi to OC/Drivers ... done
Copying Shell.efi to OC/Tools ... done
Copying GRUBShell.efi to OC/Tools ... done

Finished building /Users/hquest/Downloads/OC-tool/OUTPUT/EFI

**Comment by rusty-bits** [comment]
Thanks for the info...  

I found that I wasn't tracking the updates for Shell.efi  and OC-tool didn't notice a problem until acidanthera changed the Shell.efi to a GUID labeled build (it's still Shell.efi when placed in OC/Tools)  

using the -X option caused the whole OpenCoreShell repo to be rebuilt, thus skipping the problem, but I have added tracking on to Shell.efi so -X isn't needed  

OC-tool should now build and copy the latest Debug or Release version when needed as of version 2.4(090120)  

thanks, again
